version: 2.1
executors:
  job-executor:
    machine:
      image: ubuntu-2004:202101-01
jobs:
  build:
    executor:
      name: job-executor
    steps:
      - checkout
      - run:
          - mkdir vendor
          - docker build -f docker/php/Dockerfile .
