version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker/compose:1.25.5
    steps:
      - checkout
      - setup_remote_docker:
          version: "19.03.8"
          docker_layer_caching: true
      - run: |
          mkdir vendor
          docker build -f docker/php/Dockerfile .
