services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shippeo\Heimdall\:
        resource: '../../../../../*'

    Shippeo\Heimdall\Application\AddMetric:
        arguments:
            - !tagged monitoring.database
            - !service
                class: TagCollection
                factory:
                    - !service
                        class: Shippeo\Heimdall\Bridge\Symfony\Bundle\DependencyInjection\Tag\GlobalTagFactory
                    - create
                arguments:
                    - '%globalTags%'
        public: true
